# Generated by Django 2.2.12 on 2022-01-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=150)),
                ('projectid', models.CharField(max_length=150)),
                ('date_from', models.TextField(max_length=150)),
                ('from_to', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('platform_name', models.CharField(max_length=250)),
                ('open_status', models.CharField(max_length=100)),
                ('close_status', models.CharField(max_length=100)),
            ],
        ),
    ]
