# Generated by Django 2.2.12 on 2022-02-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220204_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_from',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='from_to',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='close_status',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='open_status',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
