# Generated by Django 2.2.12 on 2022-02-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220204_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_from',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='from_to',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='projects',
            name='close_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='open_status',
            field=models.CharField(max_length=100),
        ),
    ]
