# Generated by Django 2.2.12 on 2022-02-12 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220211_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='tl_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
